services:
    frontend:
        build:
            context: ./web
            dockerfile: Dockerfile
        depends_on:
            - backend
        environment:
            - CLIENT_APP_ID=637a2493-5510-40c3-86a6-9db8f3192966
            - CLIENT_APP_SCOPE=api://4251833c-b9c3-4013-afda-cbfd2cc50f3f/Read
            - REDIRECT_URL=http://localhost:3000/
            - WATCHPACK_POLLING=true
        ports:
            - "3000:3000"
        expose:
            - 3000
        networks:
            - app-network

    backend:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            - UVICORN_PORT=8000
            - REACT_APP_WEB_HOST=localhost
            - REACT_APP_WEB_PORT=3000
            - APP_ENVIRONMENT = dev"
        volumes:
            - ./api:/home/api
        ports:
            - "8080:8080"
        expose:
            - 8080
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
