services:
    frontend:
        build:
            context: ./web
            dockerfile: Dockerfile
        depends_on:
            - backend
        environment:
            - REACT_APP_API_BASE_URL=http://localhost:8000/api/
            - CLIENT_APP_ID=b44b7866-c7b3-40d2-b3aa-aa0398cb99de
            - CLIENT_APP_SCOPE=api://4251833c-b9c3-4013-afda-cbfd2cc50f3f/Read
            - REDIRECT_URL=http://localhost:3000/
            - REACT_APP_API_BASE_URL=http://localhost:8000/api
            - WATCHPACK_POLLING=true
        ports:
            - "3000:3000"
        expose:
            - 3000
        networks:
            - app-network

    backend:
        build:
            context: ./api
            dockerfile: Dockerfile
        environment:
            - UVICORN_PORT=8000
            - REACT_APP_WEB_HOST=localhost
            - REACT_APP_WEB_PORT=3000

            - APP_ENVIRONMENT = dev"
        volumes:
            - ./api:/home/api
        ports:
            - "8000:8000"
        expose:
            - 8000
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
