name: Python unittests

on:
    push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                python-version: ["3.10"]

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python-version }}
                  cache: "pip"

            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get -y install graphviz
                  sudo apt-get -y install graphviz-dev
                  python -m pip install --upgrade pip
                  python -m pip install poetry==1.8.5
                  python -m poetry install --with test --directory ./api

            - name: Run pytest
              run: python -m poetry run --directory ./api pytest ./api
